# the rooms here must correspond _exactly_ with the rooms that the philips hue bridge knows about
# the outlet names must exactly match the outlet names configured for the wemo outlets
# model your own wemo_rooms.toml after the example schema below

Office = [ "Massage Chair", "Halo Lamp",]
Bedroom = [ "Nightlight",]
"Front Porch" = ["Spotlight", "Christmas Decorations"]