name: Office
scenes:
- devices:
  - color:
      xy:
        x: 0.4575
        y: 0.4099
    id: a3011bb2-dd50-4fd9-b143-7ea03f367088
    name: Ceiling
    type: hue_white_and_color_ambiance
  - color:
      xy:
        x: 0.4575
        y: 0.4099
    id: 8d29cde5-f84e-40db-85c8-e1db3248af2a
    name: Desk
    type: hue_white_and_color_ambiance
  - color:
      xy:
        x: 0.4575
        y: 0.4099
    id: 6702934f-a255-4f2f-9f6c-e2d830237b6a
    name: Pendant
    type: hue_white_and_color_ambiance
  - color:
      xy:
        x: 0.4575
        y: 0.4099
    id: d9f21e38-5e8a-4846-8626-1b31224848c2
    name: Hue lightstrip 1
    type: hue_white_and_color_ambiance
  name: poop
